### ISSUE TITLE
Closure table not updated when the `parent` field is set with `.update()` QuerySet method

### ISSUE THREAD

**Issue by benbacardi** [ocadotechnology/django-closuretree#25]
With the following model:

``` python
class Test(ClosureModel):
    name = models.CharField(max_length=20)
    parent = models.ForeignKey('self', null=True)
    def __str__(self):
        return '{} ({})'.format(self.name, self.parent)
```

The following shows the closure table not being updated:

``` python
>>> a = Test(name='A')
>>> a.save()
>>> b = Test(name='B')
>>> b.save()
>>> c = Test(name='C', parent=a)
>>> c.save()
>>> Test.objects.get(name='A').get_descendants()
[<Test: C (A (None))>]
>>> Test.objects.get(name='B').get_descendants()
[]
>>> Test.objects.filter(name='C').update(parent=Test.objects.get(name='B'))
1
>>> Test.objects.get(name='A').get_descendants()
[<Test: C (B (None))>]
>>> Test.objects.get(name='B').get_descendants()
[]
>>> Test.rebuildtable()
>>> Test.objects.get(name='A').get_descendants()
[]
>>> Test.objects.get(name='B').get_descendants()
[<Test: C (B (None))>]
```

**Comment by mikebryant** [comment]
This is because ```update()``` doesn't call signal handlers. See here: https://docs.djangoproject.com/en/dev/topics/db/queries/#updating-multiple-objects-at-once

I'm not sure if there's anything we can do to make this work - maybe we just want an explicit note in the documentation that you can't use ```update()``` to change the parent field

**Comment by benbacardi** [comment]
I knew that would be the case, I just hoped that there might be something we could do about it :(

**Comment by COLABORATI** [comment]
Yes, please create the explicit note in the docs or describe a workaround there, thank you very much!
