### ISSUE TITLE
Fails to detect newly created instances with non auto incrementing primary keys

### ISSUE THREAD

**Issue by kbrownlees** [ocadotechnology/django-closuretree#30]
Since the create check is for self.id existing it fails if the primary key is provided or has a default value (ie if you are using a UUID primary key).

Ideally you should probably listen to the post_save signal since that has a created flag?

Otherwise, this fixes my issue:
`create = not self.id or kwargs.get('force_insert')`

**Comment by mikebryant** [comment]
Using the post_save signal sounds like a good way to go.

**Comment by mikebryant** [comment]
@kbrownlees Can you test the fix in #31 works for you?

(As an aside, is this in a public project? I'm curious to see where this library ends up being used)

**Comment by kbrownlees** [comment]
Really shouldn't write bug reports last thing on a Friday!

@mikebryant thank you for the prompt fix! Just tested it and it works for me.

It will be public, startup around project management using Kanban. Nothing to show yet though! Feel free to pop your email into https://kando.io if your interested :)

**Comment by cnk** [comment]
@mikebryant Would you mind cutting a new release and putting it on pypi? I just spent an hour or so trying to figure out why rebuildtable worked but creating new objects didn't hook them up to the tree. I am using UUIDs as primary keys so need this commit for closuretree to work for me.

Thanks,

**Comment by mikebryant** [comment]
@cnk Sorry about that. Thanks for letting us know, new release (1.1.9) is on Pypi now :)
