### ISSUE TITLE
Could not create instances: "matching query does not exist"

### ISSUE THREAD

**Issue by desfrenes** [ocadotechnology/django-closuretree#34]
Django 1.10, Postgres 9.6 with this model definition:

```
class Category(ClosureModel):
    title = models.CharField(max_length=64)
    parent = models.ForeignKey('self', related_name='children', null=True)

```
C:\Users\studio\Downloads\testproject>python manage.py shell
Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:01:18) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> from pim.models import Category
>>> c = Category(name="pompompo")
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Users\studio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\db\models\base.py", line 540, in __init__
    setattr(self, field.attname, val)
  File "C:\Users\studio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\closuretree\models.py", line 100, in __setattr__
    hasattr(self, id_field_name) and  # It's already been set
  File "C:\Users\studio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\db\models\query_utils.py", line 115, in __get__
    instance.refresh_from_db(fields=[self.field_name])
  File "C:\Users\studio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\db\models\base.py", line 685, in refresh_from_db
    db_instance = db_instance_qs.get()
  File "C:\Users\studio\AppData\Local\Programs\Python\Python35-32\lib\site-packages\django\db\models\query.py", line 385, in get
    self.model._meta.object_name
pim.models.DoesNotExist: Category matching query does not exist.

**Comment by mikebryant** [comment]
I'm trying to reproduce with Django 1.10.4, sqlite

I get:
```
In [1]: from flibble.models import Category

In [2]: c = Category(title='blah')

In [3]: c.save()
```

The example given: ```
In [5]: c = Category(name='blah')
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-5-a7e3f63500c3> in <module>()
----> 1 c = Category(name='blah')

/export/home/m/virtualenvs/django-closuretree/local/lib/python2.7/site-packages/django/db/models/base.pyc in __init__(self, *args, **kwargs)
    553                     pass
    554             if kwargs:
--> 555                 raise TypeError("'%s' is an invalid keyword argument for this function" % list(kwargs)[0])
    556         super(Model, self).__init__()
    557         signals.post_init.send(sender=self.__class__, instance=self)

TypeError: 'name' is an invalid keyword argument for this function
```
- as the model doesn't actually have a `name` field.

Is there something else in the model that's not working for you?

**Comment by mikebryant** [comment]
There was definitely a problem with Django 1.10, I'm fixing that in #35

**Comment by desfrenes** [comment]
Sweet ! 👍

**Comment by mikebryant** [comment]
@desfrenes Can you give the latest release (1.1.10) a try, and see if you're still hitting problems?

**Comment by desfrenes** [comment]
Seems to be all good :) 

```
from pim.models import Node
n1 = Node(name="root node")
n1.save()
n2 = Node(name="child node", parent=n1)
n2.save()
```

```
django=# select * from pim_node;
 id |    name    | parent_id
----+------------+-----------
  1 | root node  |
  2 | child node |         1
(2 lignes)

django=# select * from pim_nodeclosure;
 id | depth | child_id | parent_id
----+-------+----------+-----------
  1 |     0 |        1 |         1
  2 |     0 |        2 |         2
  3 |     1 |        2 |         1
(3 lignes)
```

I had to change your example code a bit, otherwise the first node wouldn't insert due to NOT NULL constraint:

```
class Node(ClosureModel):
    name = models.CharField(max_length=24)
    parent = models.ForeignKey('self', related_name='children', null=True)
```

Pretty obvious but you might want to update the docs.

Anyway thank you for the quick fix :-)

**Comment by mikebryant** [comment]
Thanks, I've got a PR open to fix the docs
