### ISSUE TITLE
Why we need parent field in main table?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [ocadotechnology/django-closuretree#44]
Hello, my friend! :) I want to realize `"Closure Table"` architecture in my Django project and I came across your project.

I tested it right now and notice that main table (lets call it `"node"`) has `parent_id` field. The second table (lets call it `"nodeclosure"`) also has `parent_id` field. In a lot of literature about `"Closure Table"` people say that there is no need to use in main table `parent_id` field cause all information about _ancestor_, _descendant_ we store in second table. My question is why you decided to use `parent_id` in main table? Is it modified version of `"Closure Table"`?

**Comment by mikebryant** [comment]
We're treating the normal table `node` as the canonical source of the data.
The closure table is being treated as a derived source, and can be rebuilt from scratch (e.g. https://github.com/ocadotechnology/django-closuretree/blob/d6e4255245366a61296fd72dbe74ae28fbcb93e6/closuretree/models.py#L134).

This was just a consequence of the way this was developed - as an addon to an existing project to add the more efficient way of computing descendants. We didn't consider changing the original data model.

**Comment by NogerbekNurzhan** [comment]
Hello, @mikebryant :) Thank you for your answer. I have little bit the same situation. My database has table (lets call it `'node'`) with `parent_id` field. This table use `"Adjacency List"` architecture as I understand. There are a lot of data in that table. As I understand with the help of your app I can create closure table, in the same time do not touch to main table. I am right? So question is where and how to run `rebuildtable` method? I am little bit confused.

**Comment by NogerbekNurzhan** [comment]
I tested right now. When I use `Node.rebuildtable()` in `views.py` file your app fill with data closure table. Great! 👍  So It mean that I don't need `parent_id` field in main table, right? Cause all information about relationship we have in closure table, right?

**Comment by mikebryant** [comment]
As I said - that's only derived data. The library relies on the `parent_id` or similar field still existing in the main table. 

I know that this means you could write a different library that only uses the closure table - but this library doesn't work like that.

**Comment by NogerbekNurzhan** [comment]
Ok, Thank you for your answers! I think I understand the main aim of your library ;)

**Comment by NogerbekNurzhan** [comment]
Can I ask you one more question. What amount of data you were working in your database?

My main table has I lot data (10k~20k) and when I run rebuildtable method you library started fill with data closure table. After some time (~1 minute) it raise error. I dont know where is the reason of exception. Is it from database or other reason. By the way I use Oracle. Do you have any ideas?
![2018-01-09 7 37 50](https://user-images.githubusercontent.com/8999232/34723415-b30bb970-f574-11e7-8c1d-80a7f37d7855.png)

**Comment by mikebryant** [comment]
Our app is somewhat complex. Instead of a straight parent relationship to itself the data was actually in a structure like A -> B -> C -> A. (That's where the ability to change parent_id comes from)

Main table for that has ~100k rows, in Postgres.

I've not seen an error like that before tbh, so I haven't got much advice to offer.
We have never run rebuildtable while also trying to run stuff live though. It's possible there's race conditions there. You might need to ensure rebuildtable finishes before trying to access the site.

**Comment by NogerbekNurzhan** [comment]
Well, I found the reason of my error. In database `parent` and `child` was `NOT NULL`. But migration files was with incorrect settings. I add `blank=True, null=True` to migration file and now it works correct. Thank you, bro! ;)
