### ISSUE TITLE
Render tree in Django template?

### ISSUE THREAD

**Issue by NogerbekNurzhan** [ocadotechnology/django-closuretree#45]
Hello, my fiend! ;) I have question: how to render tree in template with the help of your app? Is there any mechanism to make it? What can you advice?

**Comment by mikebryant** [comment]
Have a look at this: https://stackoverflow.com/a/11644588/14044

`node.all_childs` would be changed to `node.get_children`

You would first need to use https://github.com/ocadotechnology/django-closuretree/blob/d6e4255245366a61296fd72dbe74ae28fbcb93e6/closuretree/models.py#L235 on the queryset, to make it cache all of the descendant information

**Comment by NogerbekNurzhan** [comment]
Thank you to this link, my friend! :) You mean to use `prepopulate` method to `all_root_elems` (queryset of root elements)? Also how to take only roots here?! Little bit strange...

Example from the link:
<ul>
{%for node in all_root_elems %} 
    {%include "tree_view_template.html" %}
{%endfor%}
</ul>

**tree_view_template.html:**
<li> {{node.name}}
    {%if node.has_childs %}
        <ul>
         {%for ch in node. get_children %}
              {%with node=ch template_name="tree_view_template.html" %}
                   {%include template_name%}
              {%endwith%}
         {%endfor%}
         </ul>
    {%endif%}
</li>

**Comment by mikebryant** [comment]
I would expect to just be using a single root element, let's call it `node` - not a queryset.

`node.prepopulate(node.get_descendants().select_related(stuff_if_required))`

Then something like `{%include "tree_view_template.html" %}`, assuming that you've set up the template environment with `node` as a variable

**Comment by NogerbekNurzhan** [comment]
Sorry but your explanation is confusing. Please, can you show me little detailed example if it possible. I steal don't understand why I need prepopulate method, also from the link it seems like in template I need to set `all_root_elems`. `all_root_elems` queryset,  isn't it?

**Comment by mikebryant** [comment]
That link is a similar example. It's not an exact match...

Something like this. Not tested, likely has errors.
view:
```
node = Node.objects.get(pk=1)
node.prepopulate(node.get_descendants())
render_to_string('main.html', context={'node': node})
```
main.html:
```
<div>
    {%include "tree_view_template.html" %}
</div>
```
tree_view_template.html:
```
<li> {{node.name}}
        <ul>
         {%for ch in node.get_children %}
              {%with node=ch template_name="tree_view_template.html" %}
                   {%include template_name%}
              {%endwith%}
         {%endfor%}
         </ul>
</li>
```



prepopulate is used to set up the Node objects with the data from the closure table.

**Comment by NogerbekNurzhan** [comment]
Well here you show situation when root is only one. But usually there can be more roots in tree. For example:

```
A
 -A.1
   --A.1.1
   --A.1.2
 -A.2
B
 -B.1
 -B.2
 -B.3
C
```
Lets say I have such tree, and roots here are A, B, C. It's better to send full tree, isn't it?

**Comment by benbacardi** [comment]
It should be easy enough to adapt the code for that use case.

Again, not tested, likely has errors.

view:
```
nodes = Node.objects.filter(...)
for node in nodes:
    node.prepopulate(node.get_descendants())
render_to_string('main.html', context={'nodes': nodes})
```
main.html:
```
<div>
    <ul>
    {% for node in nodes %}
        {%include "tree_view_template.html" %}
    {% endfor %}
    </ul>
</div>
```
tree_view_template.html:
```
<li> {{node.name}}
        <ul>
         {%for ch in node.get_children %}
              {%with node=ch template_name="tree_view_template.html" %}
                   {%include template_name%}
              {%endwith%}
         {%endfor%}
         </ul>
</li>
```

**Comment by NogerbekNurzhan** [comment]
@benbacardi Hello! :) I tested your it now and it render me incorrect tree. I don't know why but that code duplicate entries in tree. Let me show the example.

I have 4 entry in database with next structure:
```
A
  - A.1
  - A.2
  - A.3
```

But in fact I have this tree:
```
A.2
A
  - A.1
  - A.2
  - A.3
A.1
A.3
```

Do you have any ideas why such thing happens? It's so confusing :'(

**Comment by benbacardi** [comment]
That looks to me like you're selecting all the nodes in the view, instead of just the top-level parents. You probably need something like this (obviously using your correct model and field names):

```python
nodes = Node.objects.filter(parent__isnull=True)
```

**Comment by NogerbekNurzhan** [comment]
Thank you for your answer, bro! :)  It show me correct tree now. But I have 2 last question after which will close the topic.

**1 QUESTION:**
What `prepopulate` method exactly make? I use it as you advised but it didn't affect to tree, to tree data.

**2 QUESTION:**
Lets say I have next simple tree which has 2 node:
```
A
  -B
```
I use next code: `Node.objects.filter(parent_id=0).order_by('position')`

In terminal I see 3 sql request to database.

First request take all nodes by my code. Filter them and sorts them by order_by method.

As I understand second and third request formed by your library. It make request to every node separately. This behavior slows down the speed of reading data. So my question is it possible to reduce the number of requests? What can you advice? Maybe use caching or change something in code of your library?!

```
SELECT "NODE"."ID", "NODE"."NAME", "NODE"."POSITION", "NODE"."PARENT_ID" FROM "NODE" INNER JOIN "NODECLOSURE" ON ("NODE"."ID" = "NODECLOSURE"."CHILD_ID") WHERE ("NODECLOSURE"."DEPTH" <= :arg1 AND "NODE"."PARENT_ID" = :arg0 AND NOT ("NODE"."ID" = :arg0)) ORDER BY "NODECLOSURE"."DEPTH" ASC' - PARAMS = (1, 12193, 12193); args=(1, 12193, 12193)

SELECT "NODE"."ID", "NODE"."NAME", "NODE"."POSITION", "NODE"."PARENT_ID" FROM "NODE" INNER JOIN "NODECLOSURE" ON ("NODE"."ID" = "NODECLOSURE"."CHILD_ID") WHERE ("NODECLOSURE"."DEPTH" <= :arg0 AND "NODE"."PARENT_ID" = :arg1 AND NOT ("NODE"."ID" = :arg1)) ORDER BY "NODECLOSURE"."DEPTH" ASC' - PARAMS = (1, 12194, 12194); args=(1, 12194, 12194)
```

**Comment by NogerbekNurzhan** [comment]
Hello! :) Where are you my friends? I think `get_children()` method which I use in template`{% for ch in node.get_children %}` is the reason of sql requests. I check every node if it has children. Dont know how to increase performance when reading the tree =(

**Comment by NogerbekNurzhan** [comment]
Well, for main question of this topic you guys give me answer. So I will close this topic. Optimization is another question. Right now I decided to use endless pagination for my tree but anyway let me know if you have any ideas about  optimization of `node.get_children`. Cause right now [get_children](https://github.com/ocadotechnology/django-closuretree/blob/d6e4255245366a61296fd72dbe74ae28fbcb93e6/closuretree/models.py#L248) make a lot of sql requests to database.

Thank you! :)
